const permitMap = {
  "city.user": "Quản lý tài khoản hệ thống",
  "city.role": "Quản lý nhóm quyền",
  "city.permission": "Quản lý chức năng ",
  district: "Quản lý Quận/Huyện",
  languages: "Quản lý ngôn ngữ",
  media: "Quản lý đa phương tiện",
  page: "Quản lý trang",
  snippet: "Quản lý khối dữ liệu",
  category: "Quản lý danh mục tin tức",
  news: "Quản lý tin tức",
  event: "Quản lý sự kiện",
  hotel: "Quản lý khách sạn",
  hotelType: "Quản lý loại khách sạn",
  point: "Quản lý địa điểm",
  pointType: "Quản lý loại địa điểm",
  restaurant: "Quản lý nhà hàng",
  restaurantType: "Quản lý loại nhà hàng",
  tour: "Quản lý tour du lịch",
  travelCompanies: "Quản lý công ty lữ hành",
  utilities: "Quản lý tiện ích",
  utilitiesType: "Quản lý loại tiện ích",
  room: "Quản lý thông tin phòng",
  restaurantCategory: "Quản lý loại ẩm thực",
  tourType: "Quản lý loại tour",
  destinationsType: "Quản lý số điểm đến",
  webSetting: "Quản lý WebSite",
  form: "Quản lý nhập form",
};
export default permitMap;
