const permitMap = {
  "system.user": "Quản lý tài khoản hệ thống",
  "system.role": "Quản lý nhóm quyền",
  "system.permission": "Quản lý chức năng ",
  "system.city": "Quản lý tài khoản thành phố",
  languages: "Quản lý ngôn ngữ",
  media: "Quản lý đa phương tiện",
  page: "Quản lý trang",
  snippet: "Quản lý khối dữ liệu",
  category: "Quản lý danh mục tin tức",
  news: "Quản lý tin tức",
  event: "Quản lý sự kiện",
  hotel: "Quản lý khách sạn",
  hotelType: "Quản lý loại khách sạn",
  point: "Quản lý địa điểm",
  pointType: "Quản lý loại địa điểm",
  restaurant: "Quản lý nhà hàng",
  restaurantType: "Quản lý loại nhà hàng",
  tour: "Quản lý tour du lịch",
  travelCompanies: "Quản lý công ty lữ hành",
  utilities: "Quản lý tiện ích",
  utilitiesType: "Quản lý loại tiện ích",
};
export default permitMap;
